SHELL:=/bin/bash

test:
	go test -covermode=count -coverprofile=./profile.coverprofile -parallel 5 -v ./...

verification:
	go vet ./...
	golangci-lint run --enable-all  --disable=gochecknoglobals --disable=gosec --disable=unparam --disable=funlen --disable=lll --tests=false ./...
	CGO_ENABLED=0 errcheck ./...

build:
	go build -o ./bin/ ./...
